### ISSUE TITLE
`geom:area_square_m` is not set using wof-exportify-www 

### ISSUE THREAD

**Issue by pathmapper** [whosonfirst/docker-whosonfirst-exportify#4]
`geom:area_square_m` is not set using docker wof-exportify-www https://github.com/whosonfirst/docker-whosonfirst-exportify#wof-exportify-www

Example: https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/13/commits/9e68f927269a0d45c2dd1803c799cc117e2382e7

**Comment by thisisaaronland** [comment]
It looks like the `Dockerfile` needs to be updated to install the py- `osgeo` and/or `gdal` bindings (I can never keep them straight...) The relevant code-y bits are:

* https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/mapzen/whosonfirst/export/__init__.py#L323-L359

* https://github.com/whosonfirst/docker-whosonfirst-exportify/blob/master/Dockerfile#L20-L24
